---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/v1"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/v2"
    schedule:
      interval: "daily"
