---
name: Linter

on: [pull_request]

jobs:
  lint:
    name: "Linter"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Get pnpm Store Dir Path
        id: pnpm-cache-dir-path
        run: |
          cd packages/v1
          echo "dir-v1=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
          cd ../../packages/v2
          echo "dir-v2=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache Node Modules V1
        uses: actions/cache@v4
        with:
          path: |
            packages/v1/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir-v1 }}
          key: embedded-pnpm-${{ hashFiles('packages/v1/pnpm-lock.yaml') }}
          restore-keys: |
            embedded-pnpm-

      - name: Cache Node Modules V2
        uses: actions/cache@v4
        with:
          path: |
            packages/v2/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir-v2 }}
          key: embedded-pnpm-${{ hashFiles('packages/v2/pnpm-lock.yaml') }}
          restore-keys: |
            embedded-pnpm-

      - name: Install Dependencies v1
        run: |
          cd packages/v1
          pnpm install --frozen-lockfile --silent

      - name: Install Dependencies v2
        run: |
          cd packages/v2
          pnpm install --frozen-lockfile --silent

      - name: Run Lint v1
        run: |
          cd packages/v1 && pnpm lint

      - name: Run Lint v2
        run: |
          cd packages/v2 && pnpm lint
