---
name: Linter

on: [pull_request]

jobs:
  lint:
    name: "Linter"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

mb      - name: Activate pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Get Pnpm Store Dir Path
        id: pnpm-cache-dir-path
        run: |
          cd packages/widget/legacy
          echo "dir-widget-legacy=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
          cd ../
          echo "dir-widget=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
          cd ../../packages/verify
          echo "dir-verify=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache Node Modules Widget Legacy (v1)
        uses: actions/cache@v4
        with:
          path: |
            packages/widget/legacy/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir-widget-legacy }}
          key: embedded-pnpm-${{ hashFiles('packages/widget/legacy/pnpm-lock.yaml') }}
          restore-keys: |
            embedded-pnpm-

      - name: Cache Node Modules Widget (v2)
        uses: actions/cache@v4
        with:
          path: |
            packages/widget/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir-widget }}
          key: embedded-pnpm-${{ hashFiles('packages/widget/pnpm-lock.yaml') }}
          restore-keys: |
            embedded-pnpm-

      - name: Cache Node Modules Verify
        uses: actions/cache@v4
        with:
          path: |
            packages/verify/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir-verify }}
          key: embedded-pnpm-${{ hashFiles('packages/verify/pnpm-lock.yaml') }}
          restore-keys: |
            embedded-pnpm-

      - name: Install Dependencies Widget Legacy (v1)
        run: |
          cd packages/widget/legacy
          pnpm install --frozen-lockfile --silent

      - name: Install Dependencies Widget (v2)
        run: |
          cd packages/widget
          pnpm install --frozen-lockfile --silent

      - name: Install Dependencies Verify
        run: |
          cd packages/verify
          pnpm install --frozen-lockfile --silent

      - name: Run Lint Widget Legacy (v1)
        run: |
          cd packages/widget/legacy && pnpm lint

      - name: Run Lint Widget (v2)
        run: |
          cd packages/widget && pnpm lint

      - name: Run Lint Verify
        run: |
          cd packages/verify && pnpm lint
