---
name: Linter

on: [pull_request]

jobs:
  lint:
    name: "Run Linter Package ${{ matrix.package.name }}"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        package:
          - name: v1
            path: packages/v1
            lockfile: packages/v1/pnpm-lock.yaml
          - name: v2
            path: packages/v2
            lockfile: packages/v2/pnpm-lock.yaml
          - name: v3
            path: packages/v3
            lockfile: packages/v3/pnpm-lock.yaml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup node 18.x
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Get pnpm Store Dir Path
        id: pnpm-cache-dir-path
        run: |
          cd ${{ matrix.package.path }}
          echo "dir=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache Node Modules
        uses: actions/cache@v5
        with:
          path: |
            ${{ matrix.package.path }}/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: embedded-pnpm-${{ hashFiles(matrix.package.lockfile) }}
          restore-keys: |
            embedded-pnpm-

      - name: Install Dependencies
        run: |
          cd ${{ matrix.package.path }}
          pnpm install --frozen-lockfile --silent

      - name: Run Lint
        run: |
          cd ${{ matrix.package.path }} && pnpm lint
