---
name: Tests


on: [pull_request]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Chrome dependencies
        run: |
          sudo apt update -y &&
            sudo apt install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
              libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 \
              libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
              libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
              lsb-release wget xdg-utils

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120

      - name: Enable Corepack
        run: corepack enable

      - name: Get Yarn Cache Dir Path
        id: yarn-cache-dir-path
        run: |
          cd packages/v1
          echo "::set-output name=dir-v1::$(yarn cache dir)"
          cd ../../packages/v2
          echo "::set-output name=dir-v2::$(yarn cache dir)"

      - name: Cache Node Modules V1
        uses: actions/cache@v3
        with:
          path: |
            packages/v1/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir-v1 }}
          key: embedded-yarn-${{ hashFiles('packages/v1/yarn.lock') }}
          restore-keys: |
            embedded-yarn-

      - name: Cache Node Modules V2
        uses: actions/cache@v3
        with:
          path: |
            packages/v1/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir-v2 }}
          key: embedded-yarn-${{ hashFiles('packages/v2/yarn.lock') }}
          restore-keys: |
            embedded-yarn-

      - name: Install Dependencies v1
        run: |
          cd packages/v1
          yarn install --frozen-lockfile --silent

      - name: Install Dependencies v2
        run: |
          cd packages/v2
          yarn install --frozen-lockfile --silent

      - name: Run Tests v1
        run: |
          cd packages/v1 && yarn test

      - name: Run Tests v2
        run: |
          cd packages/v2 && yarn test
