---
name: Tests

on: [pull_request]

jobs:
  tests:
    name: "Run Tests Package ${{ matrix.package.name }}"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        package:
          - name: v1
            path: packages/v1
            lockfile: packages/v1/pnpm-lock.yaml
          - name: v2
            path: packages/v2
            lockfile: packages/v2/pnpm-lock.yaml
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 18.x
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Install Chrome dependencies
        run: |
          sudo apt update -y &&
            sudo apt install -y ca-certificates fonts-liberation libappindicator3-1 libasound2t64 libatk-bridge2.0-0 \
              libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 \
              libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
              libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
              lsb-release wget xdg-utils

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 120

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Get pnpm Store Dir Path
        id: pnpm-cache-dir-path
        run: |
          cd ${{ matrix.package.path }}
          echo "dir=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ matrix.package.path }}/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: embedded-pnpm-${{ hashFiles(matrix.package.lockfile) }}
          restore-keys: |
            embedded-pnpm-

      - name: Install Dependencies
        run: |
          cd ${{ matrix.package.path }}
          pnpm install --frozen-lockfile --silent

      - name: Run Tests
        run: |
          cd ${{ matrix.package.path }} && pnpm test
