---
name: Tests


on: [pull_request]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Chrome dependencies
        run: |
          sudo apt update -y &&
            sudo apt install -y ca-certificates fonts-liberation libappindicator3-1 libasound2t64 libatk-bridge2.0-0 \
              libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 \
              libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
              libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
              lsb-release wget xdg-utils

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Get pnpm Store Dir Path
        id: pnpm-cache-dir-path
        run: |
          cd packages/widget/legacy
          echo "dir-widget-legacy=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
          cd ../
          echo "dir-widget=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"
          cd ../../packages/verify
          echo "dir-verify=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache Node Modules Widget Legacy (v1)
        uses: actions/cache@v4
        with:
          path: |
            packages/widget/legacy/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir-widget-legacy }}
          key: embedded-pnpm-${{ hashFiles('packages/widget/legacy/pnpm-lock.yaml') }}
          restore-keys: |
            embedded-pnpm-

      - name: Cache Node Modules Widget (v2)
        uses: actions/cache@v4
        with:
          path: |
            packages/widget/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir-widget }}
          key: embedded-pnpm-${{ hashFiles('packages/widget/pnpm-lock.yaml') }}
          restore-keys: |
            embedded-pnpm-

      - name: Install Dependencies Widget Legacy (v1)
        run: |
          cd packages/widget/legacy
          pnpm install --frozen-lockfile --silent

      - name: Install Dependencies Widget (v2)
        run: |
          cd packages/widget
          pnpm install --frozen-lockfile --silent

      - name: Install Dependencies Verify
        run: |
          cd packages/verify
          pnpm install --frozen-lockfile --silent

      - name: Run Tests Widget Legacy (v1)
        run: |
          cd packages/widget/legacy && pnpm test

      - name: Run Tests Widget (v2)
        run: |
          cd packages/widget && pnpm test

      - name: Run Tests Verify
        run: |
          cd packages/verify && pnpm test
